#!/usr/bin/env python
import os

import sys


def clean(messy):
    parts = messy.split(':')
    cleaned = []
    for part in parts:
        seg = os.path.normpath(part)
        if not os.path.isabs(seg):
            continue
        if seg in cleaned:
            continue
        cleaned.append(seg)

    return ':'.join(cleaned)


if __name__ == '__main__':
    if len(sys.argv) > 1:
        messy = sys.argv[1]
    else:
        messy = os.getenv('PATH', '')
    print clean(messy)
